AllCops:
  DisplayCopNames: false
  DisplayStyleGuide: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5.0
  Excludes:
    - 'bin/**/*'
    - 'spec/support/**/**'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - "**/*_spec.rb"
    - "**/*_docs.rb"

Metrics/MethodLength:
  Severity: warning
  CountComments: false
  Max: 20
  Exclude:
    - 'db/migrate/**'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
    - "**/*_docs.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/*_docs.rb"

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
    - "**/*_docs.rb"

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: never
