AllCops:
  DisplayCopNames: false
  DisplayStyleGuide: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5.0
  Excludes:
    - 'bin/**/*'
    - 'spec/support/**/**'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Severity: warning
  CountComments: false
  Max: 20
  Exclude:
    - 'db/migrate/**'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'

Style/FrozenStringLiteralComment:
  Enabled: false
