language: ruby
rvm:
  - 2.5.0
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - 'bundle exec rake db:create db:migrate RAILS_ENV=test'
script:
  - bundle exec rubocop --config .rubocop.yml app/ spec/ db/migrate
  - bundle exec rspec
env:
  - DB_USER=test
  - DB_PASSWORD=test
  - DB_NAME_TEST=test
  - DB_NAME_DEV=travis
